# Python na Vida Real: Aprenda a Ler Dados

Python na Vida Real: Aprenda a Ler Dados

Hoje vamos falar sobre como o Python é utilizado na vida real para trabalhar com dados. Mais do que apenas aprender a programar, o objetivo desta aula é entender como a programação se conecta com problemas reais das empresas, ajudando a analisar informações, tomar decisões e gerar valor a partir dos dados.

Vivemos em uma era onde praticamente tudo gera dados: aplicativos, redes sociais, sistemas de vendas, sensores, sites e até dispositivos domésticos. Empresas utilizam esses dados para entender o comportamento dos clientes, melhorar produtos, prever tendências e tomar decisões estratégicas. É exatamente nesse cenário que o Python se tornou uma das linguagens mais importantes da área de dados.

Python ganhou grande popularidade porque é uma linguagem simples de aprender, poderosa e com um enorme ecossistema de bibliotecas voltadas para análise de dados, ciência de dados e inteligência artificial. Isso permite que profissionais consigam ler arquivos, organizar informações, fazer cálculos, criar gráficos e até construir modelos de previsão com poucas linhas de código.

Algumas das bibliotecas mais utilizadas nesse universo são:

* Pandas – usada para manipulação e análise de dados em tabelas.

* NumPy – utilizada para cálculos matemáticos e operações numéricas.

* Matplotlib e Seaborn – usadas para criação de gráficos e visualizações.

* Scikit-learn – utilizada para machine learning.

* Requests – usada para coletar dados de APIs na internet.

### Áreas que utilizamos Python + Dados

Analista de Dados (Data Analyst)
Responsável por analisar dados, criar relatórios, dashboards e gerar insights para apoiar decisões do negócio.

Engenheiro de Dados (Data Engineer)
Trabalha construindo pipelines de dados, organizando grandes volumes de informação e garantindo que os dados estejam disponíveis para análise.

Cientista de Dados (Data Scientist)
Utiliza estatística, programação e machine learning para criar modelos preditivos e descobrir padrões complexos nos dados.

Analista de BI (Business Intelligence)
Focado em transformar dados em indicadores e visualizações que ajudam empresas a entender seu desempenho.

Além da diversidade de carreiras, a área de dados também se destaca pela alta demanda no mercado de trabalho. Muitas empresas estão em processo de transformação digital e precisam cada vez mais de profissionais capazes de trabalhar com dados.

Em relação aos salários, eles podem variar dependendo da cidade, empresa e experiência, mas de forma geral no Brasil temos uma média aproximada para nível júnior:

* Analista de Dados Júnior: entre 3.000 reais e 6.000 reais

* Engenheiro de Dados Júnior: entre 5.000 reais e 8.000 reais

* Cientista de Dados Júnior: entre 5.000 reais e 9.000 reais

### Pandas

O Pandas é uma das principais bibliotecas para análise de dados com Python. Trata-se de uma biblioteca open-source, ou seja, de código aberto, desenvolvida e mantida por uma grande comunidade de desenvolvedores e pesquisadores ao redor do mundo. Por ser amplamente utilizada tanto no meio acadêmico quanto no mercado, o Pandas recebe atualizações constantes, muitas vezes baseadas em problemas reais enfrentados por analistas, cientistas de dados e engenheiros de dados no dia a dia.

Na aula de hoje, focaremos principalmente em um projeto prático utilizando Pandas, com o objetivo de conhecer o poder dessa biblioteca e entender como ela pode ajudar na resolução de problemas que tradicionalmente seriam feitos em planilhas, como no Excel, mas que podem ser realizados de forma muito mais eficiente através de código.

O Pandas foi criado para facilitar a manipulação, limpeza, organização e análise de dados estruturados. Ele trabalha principalmente com duas estruturas de dados muito importantes:

* Series – uma estrutura semelhante a uma coluna de dados.

* DataFrame – uma estrutura semelhante a uma tabela ou planilha, com linhas e colunas.

### Pandas 🤜 X 🤛 Excel

Quando comparamos o Pandas com ferramentas tradicionais como o Excel, algumas vantagens se destacam:

__Automação de tarefas__
No Excel, muitas operações precisam ser feitas manualmente ou com fórmulas. Com Pandas, é possível escrever um script que executa todo o processo automaticamente, economizando tempo e reduzindo erros.

__Reprodutibilidade__
Quando utilizamos código, conseguimos reproduzir exatamente a mesma análise quantas vezes forem necessárias. Em planilhas, muitas vezes as transformações ficam difíceis de rastrear.

__Escalabilidade__
Planilhas possuem limitações quando trabalhamos com grandes volumes de dados. O Pandas consegue lidar com bases muito maiores, permitindo análises que seriam difíceis ou até impossíveis em ferramentas tradicionais.

__Integração com outras ferramentas__
Como faz parte do ecossistema Python, o Pandas pode ser facilmente integrado com outras bibliotecas de dados, como ferramentas de visualização, estatística e machine learning.

__Processos mais organizados e versionados__
Utilizando código, podemos versionar nossas análises com ferramentas como Git, algo que não é tão simples quando trabalhamos apenas com planilhas.

Isso não significa que ferramentas como Excel deixaram de ser importantes. Na verdade, elas continuam sendo muito utilizadas, principalmente para visualizações rápidas e análises exploratórias simples. Porém, quando lidamos com maior volume de dados, automação ou análises mais complexas, o uso de Python e Pandas se torna uma solução muito mais poderosa.

Por esse motivo, o Pandas acabou se tornando uma ferramenta fundamental para profissionais da área de dados, sendo amplamente utilizada em empresas de tecnologia, bancos, startups, consultorias e diversos outros setores.

Durante a aula, iremos explorar na prática como o Pandas pode nos ajudar a ler dados, manipulá-los e extrair informações importantes, mostrando como a programação pode transformar a forma como trabalhamos com dados

### Primeiros passos

Bom, nessa aula você pode iniciar o projeto localmente ou utilizar o google colab, irei ensinar das duas formas:

Para o google colab, você precisa apenas entrar na conta google e vai encontrar no mesmo local dos pontinhos que tem email, docs, etc, o colab, lá, é basicamente um servidor na nuvem que você pode criar um jupyter notebook e iniciar seus códigos Python.

Outra maneira é utilizarmos localmente com instalações básicas

pip install pandas

pip install notebook

No seu terminal

Bom, essa aula vai ficar baseada como se você estivesse rodando localmente, que de qualquer forma irá rodar se você estiver usando o colab

In [ ]:
import pandas as pd

Dessa forma importamos o pandas para nossa aplicação

Vamos criar nosso primeiro Data Frame de testes

In [ ]:
dados = {
    'Nomes': ['Felipe', 'Thalita', 'Ricardo'],
    'Idades': [25, 23, 29]
}

df = pd.DataFrame(dados)
df

     Nomes  Idades
0   Felipe      25
1  Thalita      23
2  Ricardo      29

Como falei acima, o pandas basicamente trabalha com DataFrame(tabelas) e Series(Colunas) agora, vamos criar nossa coluna

In [ ]:
s = pd.Series([1, 2, 3, 4])
s

0    1
1    2
2    3
3    4
dtype: int64

Mas, sabemos que no mercado de trabalho não vamos criar normalmente nada do 0, normalmente recebemos esses dados de algum local e fazemos a análise de dados

Então, vamos ler uma tabela real de testes

In [ ]:
df = pd.read_csv('funcionarios.csv')

In [ ]:
df

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2
2,3,Bianca Vasconcelos,44,2022-10-28,3094.55,False,2
3,4,Alice Machado,40,2023-10-10,6287.20,True,2
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4
5,6,Henry Gabriel da Mata,42,2024-01-26,4941.62,False,4
6,7,Sra. Maria Luiza Oliveira,58,2024-08-24,7111.25,True,5
7,8,Isis Marques,24,2023-02-05,8438.66,True,1
8,9,Sr. Vitor da Rosa,61,2024-03-25,2363.85,False,1
9,10,Théo Cardoso,54,2022-09-05,8029.65,True,2
10,11,Marcelo Rodrigues,57,2024-02-06,8109.35,True,1
11,12,Maria Clara Santos,39,2023-10-21,2601.68,True,4
12,13,Sofia Rios,45,2023-05-19,4990.01,False,1
13,14,Benicio das Neves,22,2022-04-15,2541.54,True,5
14,15,Levi Silveira,42,2024-02-10,9261.98,True,5
15,16,Maria Fernanda Rezende,29,2023-11-18,7436.21,False,3
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2
17,18,Davi Miguel Ribeiro,48,2022-07-10,2625.01,False,5
18,19,Dr. Mathias Montenegro,20,2023-08-17,9566.83,False,4
19,20,Samuel Gonçalves,21,2023-10-03,3884.99,True,3

Isso seria um exemplo para caso o arquivo seja um CSV, caso seja um excel, vamos ler com o read_excel

Conhecendo mais comandos para um DF:

Se tivermos um DF com muitas linhas e queremos somente conhecer como estar estruturado nosso DF, podemos utilizar o comando

In [ ]:
df.head()

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2
2,3,Bianca Vasconcelos,44,2022-10-28,3094.55,False,2
3,4,Alice Machado,40,2023-10-10,6287.20,True,2
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4

Se quisermos trabalhar com colunas específicas, podemos apenas passar os nomes, como se fosse uma estrutura de um dicionário

In [ ]:
df[['Nome', 'Data de Registro']]

                         Nome Data de Registro
0    Sra. Isabela Vasconcelos       2022-02-11
1             Heitor Teixeira       2022-01-17
2          Bianca Vasconcelos       2022-10-28
3               Alice Machado       2023-10-10
4           Antônio Fernandes       2023-08-09
5       Henry Gabriel da Mata       2024-01-26
6   Sra. Maria Luiza Oliveira       2024-08-24
7                Isis Marques       2023-02-05
8           Sr. Vitor da Rosa       2024-03-25
9                Théo Cardoso       2022-09-05
10          Marcelo Rodrigues       2024-02-06
11         Maria Clara Santos       2023-10-21
12                 Sofia Rios       2023-05-19
13          Benicio das Neves       2022-04-15
14              Levi Silveira       2024-02-10
15     Maria Fernanda Rezende       2023-11-18
16         Thomas Casa Grande       2024-03-29
17        Davi Miguel Ribeiro       2022-07-10
18     Dr. Mathias Montenegro       2023-08-17
19           Samuel Gonçalves       2023-10-03

Como aplicar filtros?

Nesse caso, podemos usar apenas como uma questão de comparação, mas não da maneira abaixo

In [ ]:
df['Idade'] > 30

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7     False
8      True
9      True
10     True
11     True
12     True
13    False
14     True
15    False
16     True
17     True
18    False
19    False
Name: Idade, dtype: bool

Dessa maneira, ele traz apenas uma Serie Booleana, informando se aquela linha é ou não maior do que 30

In [ ]:
df[df['Idade'] > 30]

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2
2,3,Bianca Vasconcelos,44,2022-10-28,3094.55,False,2
3,4,Alice Machado,40,2023-10-10,6287.20,True,2
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4
5,6,Henry Gabriel da Mata,42,2024-01-26,4941.62,False,4
6,7,Sra. Maria Luiza Oliveira,58,2024-08-24,7111.25,True,5
8,9,Sr. Vitor da Rosa,61,2024-03-25,2363.85,False,1
9,10,Théo Cardoso,54,2022-09-05,8029.65,True,2
10,11,Marcelo Rodrigues,57,2024-02-06,8109.35,True,1
11,12,Maria Clara Santos,39,2023-10-21,2601.68,True,4
12,13,Sofia Rios,45,2023-05-19,4990.01,False,1
14,15,Levi Silveira,42,2024-02-10,9261.98,True,5
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2
17,18,Davi Miguel Ribeiro,48,2022-07-10,2625.01,False,5

Combinando filtros:

In [13]:
# trazendo todos os funcionários com mais de 30 anos e que ganham mais que 5.000
filtro1 = df['Idade'] > 30
filtro2 = df['Salário'] > 5_000

df[filtro1 & filtro2]

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2
3,4,Alice Machado,40,2023-10-10,6287.20,True,2
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4
6,7,Sra. Maria Luiza Oliveira,58,2024-08-24,7111.25,True,5
9,10,Théo Cardoso,54,2022-09-05,8029.65,True,2
10,11,Marcelo Rodrigues,57,2024-02-06,8109.35,True,1
14,15,Levi Silveira,42,2024-02-10,9261.98,True,5
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2

Criando novas colunas

In [14]:
df['Salário Anual'] = df['Salário'] * 12
df

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento,Salário Anual
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4,53221.56
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2,94019.64
2,3,Bianca Vasconcelos,44,2022-10-28,3094.55,False,2,37134.60
3,4,Alice Machado,40,2023-10-10,6287.20,True,2,75446.40
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4,85661.16
5,6,Henry Gabriel da Mata,42,2024-01-26,4941.62,False,4,59299.44
6,7,Sra. Maria Luiza Oliveira,58,2024-08-24,7111.25,True,5,85335.00
7,8,Isis Marques,24,2023-02-05,8438.66,True,1,101263.92
8,9,Sr. Vitor da Rosa,61,2024-03-25,2363.85,False,1,28366.20
9,10,Théo Cardoso,54,2022-09-05,8029.65,True,2,96355.80
10,11,Marcelo Rodrigues,57,2024-02-06,8109.35,True,1,97312.20
11,12,Maria Clara Santos,39,2023-10-21,2601.68,True,4,31220.16
12,13,Sofia Rios,45,2023-05-19,4990.01,False,1,59880.12
13,14,Benicio das Neves,22,2022-04-15,2541.54,True,5,30498.48
14,15,Levi Silveira,42,2024-02-10,9261.98,True,5,111143.76
15,16,Maria Fernanda Rezende,29,2023-11-18,7436.21,False,3,89234.52
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2,98470.80
17,18,Davi Miguel Ribeiro,48,2022-07-10,2625.01,False,5,31500.12
18,19,Dr. Mathias Montenegro,20,2023-08-17,9566.83,False,4,114801.96
19,20,Samuel Gonçalves,21,2023-10-03,3884.99,True,3,46619.88

Também podemos remover as colunas de maneira bem simples

In [16]:
df = df.drop('Salário Anual', axis=1)

In [17]:
df

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2
2,3,Bianca Vasconcelos,44,2022-10-28,3094.55,False,2
3,4,Alice Machado,40,2023-10-10,6287.20,True,2
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4
5,6,Henry Gabriel da Mata,42,2024-01-26,4941.62,False,4
6,7,Sra. Maria Luiza Oliveira,58,2024-08-24,7111.25,True,5
7,8,Isis Marques,24,2023-02-05,8438.66,True,1
8,9,Sr. Vitor da Rosa,61,2024-03-25,2363.85,False,1
9,10,Théo Cardoso,54,2022-09-05,8029.65,True,2
10,11,Marcelo Rodrigues,57,2024-02-06,8109.35,True,1
11,12,Maria Clara Santos,39,2023-10-21,2601.68,True,4
12,13,Sofia Rios,45,2023-05-19,4990.01,False,1
13,14,Benicio das Neves,22,2022-04-15,2541.54,True,5
14,15,Levi Silveira,42,2024-02-10,9261.98,True,5
15,16,Maria Fernanda Rezende,29,2023-11-18,7436.21,False,3
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2
17,18,Davi Miguel Ribeiro,48,2022-07-10,2625.01,False,5
18,19,Dr. Mathias Montenegro,20,2023-08-17,9566.83,False,4
19,20,Samuel Gonçalves,21,2023-10-03,3884.99,True,3

Temos tembém alguns dos comandos mais "simples" para sabermos mais sobre nosso DataFrame

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                20 non-null     int64
 1   Nome              20 non-null     object
 2   Idade             20 non-null     int64
 3   Data de Registro  20 non-null     object
 4   Salário           20 non-null     float64
 5   Ativo             20 non-null     bool
 6   ID Departamento   20 non-null     int64
dtypes: bool(1), float64(1), int64(3), object(2)
memory usage: 1.1+ KB

In [19]:
df.describe()

             ID      Idade      Salário  ID Departamento
count  20.00000  20.000000    20.000000        20.000000
mean   10.50000  40.850000  5944.940500         3.000000
std     5.91608  12.716649  2474.638644         1.486784
min     1.00000  20.000000  2363.850000         1.000000
25%     5.75000  32.000000  3687.380000         2.000000
50%    10.50000  42.000000  6699.225000         3.000000
75%    15.25000  49.500000  8049.575000         4.000000
max    20.00000  61.000000  9566.830000         5.000000

In [20]:
df['Salário'].sum()

np.float64(118898.80999999998)

In [21]:
df['Salário'].mean()

np.float64(5944.940499999999)

###Trabalhando mais ainda com o mundo real